name: test
on: [pull_request, push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install rabbitmq
      - run: brew services start rabbitmq
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - run: go test
